### PR TITLE
TriViewer option to enforce 'keyboard mode'.

### PR DESCRIPTION
**Pull request by philipa**
I find the "selected line follows mouse" behaviour annoying. This patch makes it optional.

### CODE REVIEW

**Comment by chriswhocodes** [comment]
Hi Philip,

Thanks for this patch. This is something I've been meaning to add for a while since the mouseover TriView linking can be a little jumpy.

I need to make a minor adjustment as adding the checkbox can cause the button text to abbreviate on small screens (like my netbook 1024x600). Will tweak the patch a little and then merge.

Many thanks for your contributions!

Cheers,

Chris

**Comment by philipa** [comment]
No problem, it was a quick hack. (I feel a little guilty about passing the CheckBox around rather than introducing a proper "Options" abstraction).

Perhaps keyboard mode should be the default? I find myself with two jitwatch sessions, trying to spot differences between implementations, and switching back and forth gets tired quickly with focus-follows-mouse. IMHO, it would be preferable to click to focus a viewer, then use cursor keys, pg up/down, mouse wheel, or scroll bar to move around - just like a browser. Might also be useful to have left-cursor/right-cursor switch between the viewers.

**Comment by chriswhocodes** [comment]
Hi Philip,

I'm going to work on "keyboard mode" tonight.

Can I just confirm the problem you were having was with the mouse listener and not with the "link" feature that updates the other panes according to the location in the current one (e.g. when you change method in the src it loads the bytecode for the new method) ?

I think the keyboard mode should still have the pane linking feature otherwise you'll be left looking at the wrong bytecode / asm as you move around the source.

Cheers,

Chris

**Comment by philipa** [comment]
Correct.

Essentially I'd like only positive clicks from the mouse to mean anything. I should be able to alt tab away, do something else (e.g. read agner fog :-)), wave my pointer around while having a thing, then pick up exactly where I left off.

**Comment by chriswhocodes** [comment]
Couldn't merge this PR as it conflicted with the changes for local asm labels so wrote this functionality manually. Let me know how you find it?

**Comment by philipa** [comment]
Looks good +1

**Pull request closed without merging**
